'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useState } from 'react'
import { Activity, Bell, ChevronRight, FileText, LayoutDashboard, LockKeyhole, LogOut, Menu, Settings2, ShieldCheck, Users, Workflow, X } from 'lucide-react'

const links = [['Dashboard','/dashboard',LayoutDashboard],['Live Voice Analysis','/live-analysis',Activity],['Sessions','/sessions',FileText],['Alerts','/alerts',Bell],['Verification','/verification',ShieldCheck],['Analytics','/analytics',Workflow],['Policies','/policies',Settings2],['Users','/users',Users]] as const

export function AppShell({ title = 'Dashboard', children }: { title?: string; children?: React.ReactNode }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false)
  return <div className="min-h-screen bg-background md:flex">{open && <button aria-label="Close sidebar" className="fixed inset-0 z-30 bg-background/70 md:hidden" onClick={() => setOpen(false)} />}<aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 w-72 border-r border-border bg-card p-5 transition-transform md:static md:block md:w-64 md:translate-x-0`}><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3" onClick={() => setOpen(false)}><span className="flex size-8 items-center justify-center rounded-md border border-primary/50 bg-primary/10 text-primary"><ShieldCheck size={17}/></span><span className="font-mono text-xs font-bold tracking-[0.15em]">VOICEGUARD</span></Link><button className="p-2 md:hidden" onClick={() => setOpen(false)} aria-label="Close sidebar"><X size={18}/></button></div><div className="mt-10 mono-label">WORKSPACE</div><nav className="mt-4 flex flex-col gap-1">{links.map(([label, href, Icon]) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm ${pathname === href ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon size={16}/>{label}</Link>)}</nav><div className="mt-10 rounded-lg border border-primary/20 bg-primary/5 p-4"><LockKeyhole size={16} className="text-primary"/><p className="mt-3 text-xs leading-5 text-muted-foreground">Backend authorization and live data connect in Phase 2.</p></div><Link href="/login" className="mt-6 flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted hover:text-foreground"><LogOut size={16}/>Log out</Link></aside><div className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b border-border px-5 md:px-8"><div className="flex items-center gap-3"><button className="rounded-md p-2 text-muted-foreground hover:bg-muted md:hidden" aria-label="Open sidebar" onClick={() => setOpen(true)}><Menu size={19}/></button><div><div className="mono-label">SECURITY WORKSPACE</div><h1 className="mt-1 text-lg font-semibold">{title}</h1></div></div><Link href="/profile" className="flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><span className="flex size-8 items-center justify-center rounded-full bg-muted">FG</span><span className="hidden sm:block">Frontend Guest</span><ChevronRight size={14}/></Link></header><main className="p-5 md:p-8">{children}</main></div></div>
}
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="card-surface flex min-h-64 flex-col items-center justify-center p-8 text-center"><Activity size={26} className="text-primary"/><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p></div> }
