'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowLeft, Check, Filter, Play, Search, ShieldAlert, Square } from 'lucide-react'
import { AppShell, EmptyState } from './app-shell'

const titles: Record<string, string> = { sessions: 'Call History', alerts: 'Security Alerts', verification: 'Verification Center', analytics: 'Analytics', investigations: 'Investigations', users: 'Organization Users', policies: 'Risk Policies', reports: 'Reports & Analytics', integrations: 'Integrations', admin: 'System Administration', profile: 'Profile' }
export function FoundationPage({ section }: { section: string }) {
  const title = titles[section] || 'Dashboard'
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All')
  const [detail, setDetail] = useState('')
  const [saved, setSaved] = useState(false)
  const items = ['No connected records yet', 'Connect your backend to populate this workspace']
  const filtered = useMemo(() => items.filter(item => item.toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || filter === 'Ready')), [query, filter])
  return <AppShell title={title}><div className="flex flex-col gap-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mono-label text-primary">FRONTEND FOUNDATION</div><h2 className="mt-2 text-3xl font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">Backend data and authorization will connect in a later phase.</p></div><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft size={15}/> Dashboard</Link></div>{section === 'dashboard' ? <DashboardHome /> : <><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-muted-foreground" size={16}/><span className="sr-only">Search {title}</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}`} className="w-full rounded-md border border-input bg-card py-2.5 pl-9 pr-3 text-sm" /></label><label className="flex items-center gap-2 rounded-md border border-input bg-card px-3 text-sm"><Filter size={15} className="text-muted-foreground"/><span className="sr-only">Filter</span><select value={filter} onChange={e => setFilter(e.target.value)} className="bg-transparent py-2.5 outline-none"><option>All</option><option>Ready</option></select></label></div>{filtered.length ? <EmptyState title={items[0]} description={items[1]} /> : <EmptyState title="No matches" description="Try a different search or filter." />}</>}{detail && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-5"><div className="card-surface w-full max-w-md p-6"><div className="mono-label text-primary">FRONTEND ACTION</div><h3 className="mt-3 text-xl font-semibold">{detail}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">This action is prepared for the next integration phase. No backend operation has been performed.</p><button className="mt-6 w-full rounded-md border border-border px-4 py-2.5 text-sm hover:bg-muted" onClick={() => setDetail('')}>Close</button></div></div>}</div></AppShell>
}
function DashboardHome() { const [running, setRunning] = useState(false); const [message, setMessage] = useState(''); return <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="card-surface p-6"><div className="flex items-start justify-between"><div><div className="mono-label text-primary">LIVE VOICE ANALYSIS</div><h2 className="mt-3 text-2xl font-semibold">Ready when your pipeline is connected.</h2></div><ShieldAlert className="text-primary" size={22}/></div><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">Start and stop controls are available for the future audio pipeline. Phase 1 does not request microphone access or generate analysis output.</p>{message && <div role="status" className="mt-5 rounded-md border border-primary/30 bg-primary/10 p-3 text-xs text-primary">{message}</div>}<div className="mt-6 flex flex-wrap gap-3"><button onClick={() => { setRunning(true); setMessage('Session prepared. Audio processing integration is pending.'); }} disabled={running} className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50"><Play size={15}/> Start analysis</button><button onClick={() => { setRunning(false); setMessage('Session stopped. No analysis was performed.'); }} disabled={!running} className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2.5 text-sm disabled:opacity-50"><Square size={14}/> Stop analysis</button></div></div><div className="card-surface p-6"><div className="mono-label">SECURITY ACTIONS</div><div className="mt-5 flex flex-col gap-3"><Link href="/verification" className="rounded-md border border-border p-4 text-sm hover:border-primary">Open verification center</Link><Link href="/alerts" className="rounded-md border border-border p-4 text-sm hover:border-primary">Review security alerts</Link><Link href="/profile" className="rounded-md border border-border p-4 text-sm hover:border-primary">View profile</Link></div></div></div>}
